name: security

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install jq tool
        run: |
          sudo apt-get update
          sudo apt-get install jq
    
    
    
